version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      API_KEY: ${API_KEY}
      DATABASE_URL: ${DATABASE_URL}
      TOGETHER_API_URL: {TOGETHER_API_URL}      
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads # Mount uploads folder

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # only if you need to access the database outside docker
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: